version: '3'

services:
  db:
    image: mongo
    restart: always
    volumes:
      - data:/data/db
    networks: 
      - db

  bonita:
    image: bonita
    restart: always
    networks: 
      - bonita

  bpm:
    build: ./bpm
    restart: always
    environment: 
      BONITA_URL: 'http://bonita:8080/bonita'
    volumes: 
      - ./bpm:/usr/src/app
      - /usr/src/app/node_modules
    networks: 
      - public
      - bonita

  coupons:
    build: ./coupons
    restart: always
    environment: 
      DB_URL: 'mongodb://db/coupons'
    volumes: 
      - ./coupons:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
    networks: 
      - public
      - db

  employees:
    build: ./employees
    restart: always
    environment: 
      DB_URL: 'mongodb://db/employees'
    volumes: 
      - ./employees:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
    networks: 
      - public
      - db

  products:
    build: ./products
    restart: always
    environment: 
      DB_URL: 'mongodb://db/products'
    volumes: 
      - ./products:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
    networks: 
      - public
      - db

  # sales:
  #   build: ./sales
  #   restart: always
  #   environment: 
  #     DB_URL: 'mongodb://db/sales'
  #   volumes: 
  #     - ./sales:/usr/src/app
  #     - /usr/src/app/node_modules
  #   depends_on:
  #     - db
  #   networks: 
  #     - public
  #     - db

  users:
    build: ./users
    restart: always
    environment: 
      DB_URL: 'mongodb://db/users'
    volumes: 
      - ./users:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
    networks: 
      - public
      - db
  
  web:
    build:
      context: ./web
      dockerfile: Dockerfile-dev
    restart: always
    ports:
      - 3000:3000
    networks:
      - public
    volumes: 
      - ./web:/usr/src/app
      - /usr/src/app/node_modules
    

  proxy:
    build: ./proxy
    environment: 
      - ACME_AGREE=true
      - BONITA=bonita:8080/bonita
      - BPM_API=products:3000
      - COUPONS_API=coupons:3000
      - EMPLOYEES_API=employees:3000
      - PRODUCTS_API=products:3000
      - SALES_API=sales:3000
      - USERS_API=products:3000
      - WEB=web:3000
      - PORT=80
    restart: always
    ports: 
      - 80:80
      - 433:433
    networks:
      - public
      - bonita

volumes:
  data:

networks: 
  public:
  bonita:
  db: