version: '3'

services:
  products-api:
    build: ./products
    restart: always
    environment: 
      DB_URL: 'mongodb://products-db/products'
    volumes: 
      - ./products:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - products-db

  products-db:
    image: mongo
    restart: always
    volumes:
      - products-data:/data/db

  employees-api:
    build: ./employees
    restart: always
    environment: 
      DB_URL: 'mongodb://employees-db/employees'
    volumes: 
      - ./employees:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - employees-db

  employees-db:
    image: mongo
    restart: always
    volumes:
      - employees-data:/data/db

  coupons-api:
    build: ./coupons
    restart: always
    environment: 
      DB_URL: 'mongodb://coupons-db/coupons'
    volumes: 
      - ./coupons:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - coupons-db

  coupons-db:
    image: mongo
    restart: always
    volumes:
      - coupons-data:/data/db

  proxy:
    build: ./proxy
    environment: 
      - ACME_AGREE=true
      - EMPLOYEES_API=employees-api
      - EMPLOYEES_PORT=3000
      - PRODUCTS_API=products-api
      - PRODUCTS_PORT=3000
    restart: always
    ports: 
      - 80:80
      - 433:433
    depends_on:
      - employees-api
      - products-api
      - coupons-api

volumes:
  products-data:
  employees-data:
  coupons-data: